[project]
name = "hedgedoc-backup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "httpx>=0.28.1",
    "markdown>=3.8",
]

[tool.ruff.lint]
ignore = ["CPY001"]
